---
- hosts: all
  tasks:
    - file: src={{ playbook_dir }}/files/{{ item }} dest=~/.{{ item }} state=link force=yes
      with_items:
        - bashrc
        - bash_profile
        - bash_aliases
        - gitconfig
