---
- hosts: all
  tasks:
    - copy: src={{ playbook_dir }}/files/{{ item }} dest=~/.{{ item }}
      with_items:
        - 'git-prompt.sh'

    - file: src={{ playbook_dir }}/files/{{ item }} dest=~/.{{ item }} state=link force=yes
      with_items:
        - bashrc
        - inputrc
        - bash_profile
        - bash_aliases
