if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# Turn off suspend and resume terminal feature - now we can use Ctrl+s as Ctrl+r but in opposite direction
stty -ixon

# Turn on extended glob patterns: ?() *() +() @() !()
shopt -s extglob

############# History configuration #################

# Appending history instead of rewriting
shopt -s histappend

# Ignore duplicates while appending and erase duplicates from old history
HISTCONTROL=ignoredups:erasedups

# Ignore aliases and some other patterns when write history
HISTIGNORE="$(alias | cut -d' ' -f2 | cut -d'=' -f1 | tr '\n' ':')[bf]g:exit:pwd:ls:cd:vi"

############# Prompt configuration #################

# Set number of direcories shown by \w prompt code
PROMPT_DIRTRIM=2

if [ -f ~/.git-prompt.sh ]; then
  . ~/.git-prompt.sh
fi
# Show unstaged (*) and staged (+) changes next to the branch name.
GIT_PS1_SHOWDIRTYSTATE=1
# If something is stashed, then a '$' will be shown next to the branch name.
GIT_PS1_SHOWSTASHSTATE=1
# If there're untracked files, then a '%' will be shown next to the branch name.
GIT_PS1_SHOWUNTRACKEDFILES=1
# Show the difference between HEAD and its upstream with number of commits ahead/behind (+/-) upstream
GIT_PS1_SHOWUPSTREAM="auto verbose"

# Real-time history synchronization between the terminals
# Call this function from prompt command if you want turn on this feature
sync_history() {
  history -n; # Append the history lines not already read from the history file to the current history list.
  history -w; # Write out the current history list to the history file.
  history -c; # Clear the history list. This may be combined with the other options to replace the history list completely.
  history -r; # Read the history file and append its contents to the history list.
}

set_prompt () {
  gray='\[\e[37m\]'
  cyan='\[\e[36m\]'
  reset='\[\e[00m\]'
  PS1=" $gray\\w$cyan$(__git_ps1)$reset $ "
}
PROMPT_COMMAND=set_prompt

# Setting up bash-completion on mac os
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# Start and prepare docker machine
dm-prepare
