# Listing
alias l='ls -lhF'
alias ll='ls -alhF'
alias llt='ls -alhFt'

# Vagrant
alias vg='vagrant'
alias vst='vagrant up && vagrant ssh -c "tmux -CC"'
alias vgs='vagrant status'
alias vggs='vagrant global-status'

# Git
alias g='git'
alias gs='git status'
alias gco='git checkout'

# Docker
alias dc='docker-compose'

 # OS X Specific Tools
if [ $OSTYPE = 'darwin14' ]; then
  alias dm='docker-machine'
  alias htop='sudo htop'
fi
